
package dev.amf.pw2_ex_xml;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Big", targetNamespace = "http://pw2_ex_xml.amf.dev/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Big {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversaoNOS", targetNamespace = "http://pw2_ex_xml.amf.dev/", className = "dev.amf.pw2_ex_xml.ConversaoNOS")
    @ResponseWrapper(localName = "conversaoNOSResponse", targetNamespace = "http://pw2_ex_xml.amf.dev/", className = "dev.amf.pw2_ex_xml.ConversaoNOSResponse")
    public double conversaoNOS(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversaoMPH", targetNamespace = "http://pw2_ex_xml.amf.dev/", className = "dev.amf.pw2_ex_xml.ConversaoMPH")
    @ResponseWrapper(localName = "conversaoMPHResponse", targetNamespace = "http://pw2_ex_xml.amf.dev/", className = "dev.amf.pw2_ex_xml.ConversaoMPHResponse")
    public double conversaoMPH(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
